services:
  postgres:
    image: postgres:16
    container_name: pg4e_postgres
    environment:
      POSTGRES_USER: shubhendu
      POSTGRES_PASSWORD: some_random_password
      POSTGRES_DB: pg4e
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shubhendu -d pg4e"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
