CREATE TABLE make (
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) UNIQUE
);

CREATE TABLE model (
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) UNIQUE,
    make_id INTEGER REFERENCES make(id) ON DELETE CASCADE
)